# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 842)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Home.setObjectName("Home")
        self.frame_2 = QtWidgets.QFrame(self.Home)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 794, 768))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(5, 5, 786, 756))
        self.widget.setObjectName("widget")
        self.verticalLayout_Home = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_Home.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_Home.setSpacing(6)
        self.verticalLayout_Home.setObjectName("verticalLayout_Home")
        self.groupBox_HomeRabbits = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_HomeRabbits.sizePolicy().hasHeightForWidth())
        self.groupBox_HomeRabbits.setSizePolicy(sizePolicy)
        self.groupBox_HomeRabbits.setObjectName("groupBox_HomeRabbits")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_HomeRabbits)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_Rabbits = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Rabbits.setSpacing(6)
        self.horizontalLayout_Rabbits.setObjectName("horizontalLayout_Rabbits")
        self.pushButton_RabbitsActive = QtWidgets.QPushButton(self.groupBox_HomeRabbits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RabbitsActive.sizePolicy().hasHeightForWidth())
        self.pushButton_RabbitsActive.setSizePolicy(sizePolicy)
        self.pushButton_RabbitsActive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                              ))
        self.pushButton_RabbitsActive.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_RabbitsActive.setIcon(icon)
        self.pushButton_RabbitsActive.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_RabbitsActive.setCheckable(False)
        self.pushButton_RabbitsActive.setObjectName("pushButton_RabbitsActive")
        self.horizontalLayout_Rabbits.addWidget(self.pushButton_RabbitsActive)
        self.pushButton_RabbitsAddNew = QtWidgets.QPushButton(self.groupBox_HomeRabbits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RabbitsAddNew.sizePolicy().hasHeightForWidth())
        self.pushButton_RabbitsAddNew.setSizePolicy(sizePolicy)
        self.pushButton_RabbitsAddNew.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                              ))
        self.pushButton_RabbitsAddNew.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_RabbitsAddNew.setIcon(icon)
        self.pushButton_RabbitsAddNew.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_RabbitsAddNew.setCheckable(False)
        self.pushButton_RabbitsAddNew.setObjectName("pushButton_RabbitsAddNew")
        self.horizontalLayout_Rabbits.addWidget(self.pushButton_RabbitsAddNew)
        self.pushButton_RabbitsFind = QtWidgets.QPushButton(self.groupBox_HomeRabbits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RabbitsFind.sizePolicy().hasHeightForWidth())
        self.pushButton_RabbitsFind.setSizePolicy(sizePolicy)
        self.pushButton_RabbitsFind.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                            ))
        self.pushButton_RabbitsFind.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_RabbitsFind.setIcon(icon)
        self.pushButton_RabbitsFind.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_RabbitsFind.setCheckable(False)
        self.pushButton_RabbitsFind.setObjectName("pushButton_RabbitsFind")
        self.horizontalLayout_Rabbits.addWidget(self.pushButton_RabbitsFind)
        self.pushButton_RabbitsListAll = QtWidgets.QPushButton(self.groupBox_HomeRabbits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RabbitsListAll.sizePolicy().hasHeightForWidth())
        self.pushButton_RabbitsListAll.setSizePolicy(sizePolicy)
        self.pushButton_RabbitsListAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                               ))
        self.pushButton_RabbitsListAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_RabbitsListAll.setIcon(icon)
        self.pushButton_RabbitsListAll.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_RabbitsListAll.setCheckable(False)
        self.pushButton_RabbitsListAll.setObjectName("pushButton_RabbitsListAll")
        self.horizontalLayout_Rabbits.addWidget(self.pushButton_RabbitsListAll)
        self.horizontalLayout.addLayout(self.horizontalLayout_Rabbits)
        self.verticalLayout_Home.addWidget(self.groupBox_HomeRabbits)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_Home.addWidget(self.line)
        self.groupBox_HomeBreeding = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_HomeBreeding.sizePolicy().hasHeightForWidth())
        self.groupBox_HomeBreeding.setSizePolicy(sizePolicy)
        self.groupBox_HomeBreeding.setObjectName("groupBox_HomeBreeding")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_HomeBreeding)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_Breeding = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Breeding.setSpacing(6)
        self.horizontalLayout_Breeding.setObjectName("horizontalLayout_Breeding")
        self.pushButton_BreedingDoes = QtWidgets.QPushButton(self.groupBox_HomeBreeding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BreedingDoes.sizePolicy().hasHeightForWidth())
        self.pushButton_BreedingDoes.setSizePolicy(sizePolicy)
        self.pushButton_BreedingDoes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                             ))
        self.pushButton_BreedingDoes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BreedingDoes.setIcon(icon)
        self.pushButton_BreedingDoes.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_BreedingDoes.setCheckable(False)
        self.pushButton_BreedingDoes.setObjectName("pushButton_BreedingDoes")
        self.horizontalLayout_Breeding.addWidget(self.pushButton_BreedingDoes)
        self.pushButton_BreedingAddNew = QtWidgets.QPushButton(self.groupBox_HomeBreeding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BreedingAddNew.sizePolicy().hasHeightForWidth())
        self.pushButton_BreedingAddNew.setSizePolicy(sizePolicy)
        self.pushButton_BreedingAddNew.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                               ))
        self.pushButton_BreedingAddNew.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BreedingAddNew.setIcon(icon)
        self.pushButton_BreedingAddNew.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_BreedingAddNew.setCheckable(False)
        self.pushButton_BreedingAddNew.setObjectName("pushButton_BreedingAddNew")
        self.horizontalLayout_Breeding.addWidget(self.pushButton_BreedingAddNew)
        self.pushButton_BreedingBlank = QtWidgets.QPushButton(self.groupBox_HomeBreeding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BreedingBlank.sizePolicy().hasHeightForWidth())
        self.pushButton_BreedingBlank.setSizePolicy(sizePolicy)
        self.pushButton_BreedingBlank.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                              ))
        self.pushButton_BreedingBlank.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BreedingBlank.setText("")
        self.pushButton_BreedingBlank.setIcon(icon)
        self.pushButton_BreedingBlank.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_BreedingBlank.setCheckable(False)
        self.pushButton_BreedingBlank.setObjectName("pushButton_BreedingBlank")
        self.horizontalLayout_Breeding.addWidget(self.pushButton_BreedingBlank)
        self.pushButton_BreedingBlank_2 = QtWidgets.QPushButton(self.groupBox_HomeBreeding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BreedingBlank_2.sizePolicy().hasHeightForWidth())
        self.pushButton_BreedingBlank_2.setSizePolicy(sizePolicy)
        self.pushButton_BreedingBlank_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                                ))
        self.pushButton_BreedingBlank_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_BreedingBlank_2.setText("")
        self.pushButton_BreedingBlank_2.setIcon(icon)
        self.pushButton_BreedingBlank_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_BreedingBlank_2.setCheckable(False)
        self.pushButton_BreedingBlank_2.setObjectName("pushButton_BreedingBlank_2")
        self.horizontalLayout_Breeding.addWidget(self.pushButton_BreedingBlank_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_Breeding)
        self.verticalLayout_Home.addWidget(self.groupBox_HomeBreeding)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_Home.addWidget(self.line_2)
        self.groupBox_HomeSettings = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_HomeSettings.sizePolicy().hasHeightForWidth())
        self.groupBox_HomeSettings.setSizePolicy(sizePolicy)
        self.groupBox_HomeSettings.setObjectName("groupBox_HomeSettings")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_HomeSettings)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_Settings = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Settings.setSpacing(6)
        self.horizontalLayout_Settings.setObjectName("horizontalLayout_Settings")
        self.pushButton_Settings = QtWidgets.QPushButton(self.groupBox_HomeSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Settings.sizePolicy().hasHeightForWidth())
        self.pushButton_Settings.setSizePolicy(sizePolicy)
        self.pushButton_Settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                         ))
        self.pushButton_Settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Settings.setIcon(icon)
        self.pushButton_Settings.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_Settings.setCheckable(False)
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.horizontalLayout_Settings.addWidget(self.pushButton_Settings)
        self.pushButton_Settings_2 = QtWidgets.QPushButton(self.groupBox_HomeSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Settings_2.sizePolicy().hasHeightForWidth())
        self.pushButton_Settings_2.setSizePolicy(sizePolicy)
        self.pushButton_Settings_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                           ))
        self.pushButton_Settings_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Settings_2.setText("")
        self.pushButton_Settings_2.setIcon(icon)
        self.pushButton_Settings_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_Settings_2.setCheckable(False)
        self.pushButton_Settings_2.setObjectName("pushButton_Settings_2")
        self.horizontalLayout_Settings.addWidget(self.pushButton_Settings_2)
        self.pushButton_Settings_3 = QtWidgets.QPushButton(self.groupBox_HomeSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Settings_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Settings_3.setSizePolicy(sizePolicy)
        self.pushButton_Settings_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                           ))
        self.pushButton_Settings_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Settings_3.setText("")
        self.pushButton_Settings_3.setIcon(icon)
        self.pushButton_Settings_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_Settings_3.setCheckable(False)
        self.pushButton_Settings_3.setObjectName("pushButton_Settings_3")
        self.horizontalLayout_Settings.addWidget(self.pushButton_Settings_3)
        self.pushButton_Settings_4 = QtWidgets.QPushButton(self.groupBox_HomeSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Settings_4.sizePolicy().hasHeightForWidth())
        self.pushButton_Settings_4.setSizePolicy(sizePolicy)
        self.pushButton_Settings_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                           ))
        self.pushButton_Settings_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Settings_4.setText("")
        self.pushButton_Settings_4.setIcon(icon)
        self.pushButton_Settings_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_Settings_4.setCheckable(False)
        self.pushButton_Settings_4.setObjectName("pushButton_Settings_4")
        self.horizontalLayout_Settings.addWidget(self.pushButton_Settings_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_Settings)
        self.verticalLayout_Home.addWidget(self.groupBox_HomeSettings)
        self.tabWidget.addTab(self.Home, "")
        self.Rabbits = QtWidgets.QWidget()
        self.Rabbits.setObjectName("Rabbits")
        self.frame_RabbitsMain = QtWidgets.QFrame(self.Rabbits)
        self.frame_RabbitsMain.setGeometry(QtCore.QRect(0, 0, 798, 798))
        self.frame_RabbitsMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RabbitsMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_RabbitsMain.setObjectName("frame_RabbitsMain")
        self.listWidget = QtWidgets.QListWidget(self.frame_RabbitsMain)
        self.listWidget.setGeometry(QtCore.QRect(190, 190, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit_SetName = QtWidgets.QLineEdit(self.frame_RabbitsMain)
        self.lineEdit_SetName.setGeometry(QtCore.QRect(80, 95, 113, 24))
        self.lineEdit_SetName.setObjectName("lineEdit_SetName")
        self.comboBox = QtWidgets.QComboBox(self.frame_RabbitsMain)
        self.comboBox.setGeometry(QtCore.QRect(40, 165, 79, 24))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.frame_RabbitsMain)
        self.label.setGeometry(QtCore.QRect(560, 50, 58, 16))
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.frame_RabbitsMain)
        self.listView.setGeometry(QtCore.QRect(485, 275, 256, 192))
        self.listView.setObjectName("listView")
        self.pushButton_Close = QtWidgets.QPushButton(self.frame_RabbitsMain)
        self.pushButton_Close.setGeometry(QtCore.QRect(235, 500, 80, 24))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.tabWidget.addTab(self.Rabbits, "")
        self.Breeding = QtWidgets.QWidget()
        self.Breeding.setObjectName("Breeding")
        self.tabWidget.addTab(self.Breeding, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_HomeRabbits.setTitle(_translate("MainWindow", "Rabbits"))
        self.pushButton_RabbitsActive.setText(_translate("MainWindow", "Active Rabbits"))
        self.pushButton_RabbitsAddNew.setText(_translate("MainWindow", "Add New Rabbits"))
        self.pushButton_RabbitsFind.setText(_translate("MainWindow", "Find a Rabbit"))
        self.pushButton_RabbitsListAll.setText(_translate("MainWindow", "Rabbitry"))
        self.groupBox_HomeBreeding.setTitle(_translate("MainWindow", "Breeding"))
        self.pushButton_BreedingDoes.setText(_translate("MainWindow", "Breeding Does"))
        self.pushButton_BreedingAddNew.setText(_translate("MainWindow", "Add New Breeding"))
        self.groupBox_HomeSettings.setTitle(_translate("MainWindow", "Settings"))
        self.pushButton_Settings.setText(_translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_Close.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Rabbits), _translate("MainWindow", "Rabbits"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Breeding), _translate("MainWindow", "Breeding"))
